# .github/dependabot.yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for pip (Python)
  - package-ecosystem: "pip" # Ecosystem für Python-Abhängigkeiten
    directory: "/" # Wo sich die requirements.txt befindet (Wurzelverzeichnis des Repos)
    schedule:
      interval: "weekly" # Überprüfe wöchentlich auf Updates
    # Optional: labels:
    #   - "dependencies"
    #   - "python"
    # Optional: assignees:
    #   - "dein-github-username"
    # Optional: reviewers:
    #   - "dein-github-username"
