name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: '396694012221'
  SERVICE_NAME: 'podcast-tracker-app'
  REGION: 'europe-west3'
  IMAGE_NAME: 'gcr.io/396694012221/podcast-tracker-app'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool-tsp/providers/github-actions-tsp'
          service_account: 'github-actions-deployer@amiable-mix-465520-u7.iam.gserviceaccount.com'
          # KORRIGIERT: Die 'audience' muss dem Wert entsprechen, den GitHub tatsächlich sendet (Repository-Besitzer)
          # Basierend auf dem letzten Fehler: https://github.com/thspeil
          audience: 'https://github.com/thspeil' 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.IMAGE_NAME }}:latest
          region: ${{ env.REGION }}
          env_vars: |
            DATABASE_URL=${{ secrets.NEON_DATABASE_URL }}
          flags: --allow-unauthenticated --port 5000
