name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read # Erforderlich, um den Code auszuchecken
  id-token: write # Erforderlich für Workload Identity Federation (OIDC)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "Tests werden hier ausgeführt..."

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/396694012221/locations/global/workloadIdentityPools/github-podtracker-pool-tsp/providers/github-codespaces'
        service_account: 'my-service-account@amiable-mix-465520-u7.iam.gserviceaccount.com'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Google Container Registry
      run: |-
        gcloud auth configure-docker gcr.io --quiet

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gcr.io/amiable-mix-465520-u7/podtracker-image:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: podcast-tracker-app
        image: gcr.io/amiable-mix-465520-u7/podtracker-image:latest
        region: europe-west3
        flags: --allow-unauthenticated # KORREKTUR: Dies ist der Weg, um --allow-unauthenticated zu übergeben